### ISSUE TITLE
Jacoco 설정, Redis 적용 (Refresh token) 및 카카오 로그인 구현 

### ISSUE THREAD

**Issue by HunSeongPark** [dnd-side-project/dnd-8th-2-backend#11]
## 🔥 Issue
카카오 로그인 구현 + Redis 적용 Refresh Token 관리

## ✅ TODO
- [x] Jacoco 의존성 추가 및 설정 (Test Coverage 70%, 테스트 범위 Controller, Service로 설정)
- [x] Redis / Embedded-Redis (for test) 의존성 추가 
- [x] JWT 의존성 추가
- [x] 카카오 api 호출을 위한 Http Client 의존성 추가
- [x] 카카오 로그인 구현
- [x] access token을 검증하는 인증 필터 구현
- [x] refresh 로직 구현
- [x] Redis 관련 테스트 코드 작성
