### ISSUE TITLE
Swagger 의존성 추가 및 설정

### ISSUE THREAD

**Issue by Wo-ogie** [dnd-side-project/dnd-8th-2-backend#14]
## 🔥 Issue
API 명세를 위한 swagger를 추가하고 필요한 설정을 적용한다.

## ✅ TODO
- [x] Swagger 의존성 추가
- [x] Swagger 설정
  - [x] API 명세서에 제목, 설명, 버전 명시
  - [x] API 명세서에 GitHub 링크 첨부
  - [x] Access token 관련 설정
