### ISSUE TITLE
Actuator에서 제공하는 health check 엔드포인트 사용 변경

### ISSUE THREAD

**Issue by HunSeongPark** [dnd-side-project/dnd-8th-2-backend#15]
## 🔥 Issue
기존에 직접 구현한 health check 엔드포인트를 제거하고
Actuator에서 제공하는 health check 엔드포인트를 사용해 health check을 하도록 변경한다.

## ✅ TODO
- [x]  SecurityConfig에서 white list에 추가된 health check 엔드포인트 변경 (`/api/health` to `/actuator/health`)
- [x] 기존 `/api/health` 엔드포인트 제거
- [x] CI/CD health check 쉘 스크립트 `/actuator/health` 엔드포인트로 변경
- [x] Nginx 내 스프링 서버 포트포워딩 location `/api`에서 `/`로 변경
