### ISSUE TITLE
로그인한 사용자 정보 조회 기능 구현

### ISSUE THREAD

**Issue by HunSeongPark** [dnd-side-project/dnd-8th-2-backend#24]
## 🔥 Issue
로그인한 사용자 정보 조회 기능을 구현한다.

## ✅ TODO
- [x] 로그인한 사용자 정보 조회 엔드포인트 추가
- [x] 사용자 정보 조회 로직 구현
- [x] 테스트 코드 작성
- [x] Swagger 문서 작성
