### ISSUE TITLE
장소 목록 조회 기능 구현

### ISSUE THREAD

**Issue by HunSeongPark** [dnd-side-project/dnd-8th-2-backend#35]
## 🔥 Issue
장소 목록 조회 기능을 구현한다.

## ✅ TODO
- [x] 장소 목록 조회 (카카오 서버 통신) 로직 구현
- [x] 장소 목록 조회 로직 구현 (w/ 북마크 여부 조회)
- [x] 장소 목록 조회 엔드포인트 추가
