### ISSUE TITLE
북마크 생성 API 구현

### ISSUE THREAD

**Issue by Wo-ogie** [dnd-side-project/dnd-8th-2-backend#37]
## 🔥 Issue
북마크를 생성 API를 구현한다.
만약 필요한 장소가 존재하지 않으면 장소도 생성하여 저장한다.

## ✅ TODO
- [x] 북마크 생성/저장 기능
- [x] 장소 생성/저장 기능
- [x] 북마크 생성 시 이미 북마크 했던 장소는 아닌지 검증

**Comment by Wo-ogie** [comment]
북마크를 생성하기 전에 
마킹하고자 하는 장소가 이전에 북마크 했던 장소인지 검증하는 로직을 추가하고자 issue를 reopen한다.
