### ISSUE TITLE
Develop CI, Main CI/CD 설정 및 Nginx 무중단 배포 설정

### ISSUE THREAD

**Issue by HunSeongPark** [dnd-side-project/dnd-8th-2-backend#5]
## 🔥 Issue
Develop CI, Main CI/CD 설정 및 무중단 배포 설정 

## ✅ TODO
- [x] AWS EC2 - S3 - CodeDeploy 배포 설정
- [x] Github Actions main branch CI/CD 설정
- [x] Github Actions develop branch CI 설정
- [x] 리버스 프록시 설정 (80 to 8081, 8082)
- [x] 무중단 배포 설정
