### ISSUE TITLE
북마크에 썸네일 이미지 추가

### ISSUE THREAD

**Issue by Wo-ogie** [dnd-side-project/dnd-8th-2-backend#56]
## 🔥 Issue
북마크에 썸네일 이미지 추가

## ✅ TODO
- [x]  `Bookmark` domain class에 thumbnail image url 추가
- [x] 북마크 생성 시 kakao map page에서 thumbnail image scraping 로직 추가
  - [x] JSoup 의존성 추가
