### ISSUE TITLE
Exception 처리 환경 구축

### ISSUE THREAD

**Issue by Wo-ogie** [dnd-side-project/dnd-8th-2-backend#6]
## 🔥 Issue
`@ControllerAdvice`를 활용한 예외 처리 환경을 구축한다. 

## ✅ TODO
- [x]  Custom exception template 생성
- [x] `@ControllerAdvice` 기반 exception 처리 환경 구축
  - [x] Custom exception 처리 환경 구축
  - [x] Spring 또는 그 외의 exception을 처리할 환경 구축
- [x] 기본 예외처리 로직 수정 - `ResponseEntityExceptionHandler` 상속 받아 구현
- [x] Validation error에 대한 응답 데이터 변경 - #18

**Comment by Wo-ogie** [comment]
Spring 기본 예외 중 누락된 예외가 있어서 issue를 reopen하고 추가 정의하고자 한다.

**Comment by Wo-ogie** [comment]
기본 예외처리 로직이 현재 빈약하여(exception handler에서 처리되지 않는 예외들이 다수 있음) `ResponseEntityExceptionHandler`를 상속받아 기본 예외를 처리하도록 로직을 수정하고자 한다.
이에 issue를 reopen 함.
