### ISSUE TITLE
사용자 검색기록 저장

### ISSUE THREAD

**Issue by HunSeongPark** [dnd-side-project/dnd-8th-2-backend#86]
## 🔥 Issue
사용자 검색기록 저장 (최대 20개)

## ✅ TODO
- [x] Search Table 추가
- [x] 검색 시 검색기록 저장 로직 추가
- [x] 검색기록 조회 API 추가
- [x] 검색기록 조회 API Controller, Service 테스트 코드 작성
