### ISSUE TITLE
검색기록 삭제 / 카테고리 필터 수정

### ISSUE THREAD

**Issue by HunSeongPark** [dnd-side-project/dnd-8th-2-backend#91]
## 🔥 Issue
1. 검색기록 삭제(단건, 전체)를 구현한다.
2. 카테고리 필터 수정 로직을 구현한다.

## ✅ TODO
- [x] 검색기록 삭제 API 구현 (단건)
- [x] 검색기록 삭제 API 구현 (전체)
- [x] 검색기록 삭제 테스트코드 작성
- [x] 카테고리 필터 수정 API 구현
- [x] 장소 목록 조회 시 DB 내 카테고리 필터 데이터 바라보도록 API 수정
